// ===== ДАННЫЕ ТОВАРОВ AURA ATELIER =====
// Этот файл содержит все данные о товарах
// Легко редактировать и добавлять новые товары

const PRODUCTS_DATA = [
    {
        id: 1,
        name: "Aris 222 VIP Bleck",
        description: "Эксклюзивный арабский парфюм с глубокими нотами. Идеальный выбор для особых случаев.",
        price: 4500,
        oldPrice: 5000,
        category: "arabian",
        volume: 100,
        rating: 4.8,
        reviews: 128,
        image: "https://images.satu.kz/227064425_w700_h500_maslyanye-duhi-al.jpg",
        badge: "sale",
        inStock: true,
        popular: true,
        notes: ["ладан", "кожа", "специи", "амбра"]
    },
    {
        id: 2,
        name: "Chanel №5 L'EAU",
        description: "Современная интерпретация классики с цитрусовыми и цветочными нотами.",
        price: 8900,
        oldPrice: 10500,
        category: "premium",
        volume: 100,
        rating: 4.9,
        reviews: 256,
        image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "hit",
        inStock: true,
        popular: true,
        notes: ["цитрус", "цветы", "мускус", "ваниль"]
    },
    {
        id: 3,
        name: "Zara Tobacco Collection",
        description: "Доступный аромат с нотами табака, ванили и древесины. Идеален на каждый день.",
        price: 1999,
        oldPrice: 2499,
        category: "affordable",
        volume: 100,
        rating: 4.3,
        reviews: 89,
        image: "https://images.unsplash.com/photo-1590736969956-6d9c2a8d6971?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "sale",
        inStock: true,
        popular: false,
        notes: ["табак", "ваниль", "древесина", "пряности"]
    },
    {
        id: 4,
        name: "Oud Ispahan Dior",
        description: "Роскошный арабский уд с нотами розы, сандала и пачули. Для особых вечеров.",
        price: 42000,
        oldPrice: 0,
        category: "arabian",
        volume: 75,
        rating: 4.9,
        reviews: 67,
        image: "https://images.unsplash.com/photo-1590736969956-6d9c2a8d6971?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "new",
        inStock: true,
        popular: true,
        notes: ["уд", "роза", "сандал", "пачули"]
    },
    {
        id: 5,
        name: "Jo Malone Wood Sage",
        description: "Уникальный аромат с нотами шалфея, морской соли и древесины.",
        price: 12500,
        oldPrice: 14500,
        category: "premium",
        volume: 100,
        rating: 4.7,
        reviews: 187,
        image: "https://images.unsplash.com/photo-1541643600914-78b084683601?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "hit",
        inStock: true,
        popular: true,
        notes: ["шалфей", "морская соль", "древесина", "амбра"]
    },
    {
        id: 6,
        name: "Montblanc Explorer",
        description: "Современный мужской аромат с аккордами бергамота, кедра и пачули.",
        price: 6500,
        oldPrice: 0,
        category: "affordable",
        volume: 100,
        rating: 4.5,
        reviews: 92,
        image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: null,
        inStock: true,
        popular: false,
        notes: ["бергамот", "кедр", "пачули", "мускус"]
    },
    {
        id: 7,
        name: "Tom Ford Black Orchid",
        description: "Чувственный аромат с нотами черной трюфели, орхидеи и пачули.",
        price: 18500,
        oldPrice: 21000,
        category: "premium",
        volume: 100,
        rating: 4.8,
        reviews: 143,
        image: "https://images.unsplash.com/photo-1541643600914-78b084683601?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "sale",
        inStock: true,
        popular: true,
        notes: ["трюфель", "орхидея", "пачули", "ваниль"]
    },
    {
        id: 8,
        name: "Lattafa Oud Mood",
        description: "Аутентичный арабский аромат с глубокими нотами уда и розы.",
        price: 3500,
        oldPrice: 0,
        category: "arabian",
        volume: 100,
        rating: 4.6,
        reviews: 56,
        image: "https://images.unsplash.com/photo-1590736969956-6d9c2a8d6971?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "new",
        inStock: true,
        popular: true,
        notes: ["уд", "роза", "амбра", "сандал"]
    },
    {
        id: 9,
        name: "Davidoff Cool Water",
        description: "Классический свежий аромат с нотами моря и свежести.",
        price: 3800,
        oldPrice: 4500,
        category: "affordable",
        volume: 125,
        rating: 4.4,
        reviews: 234,
        image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "sale",
        inStock: true,
        popular: true,
        notes: ["морские ноты", "свежесть", "мускус", "цитрус"]
    },
    {
        id: 10,
        name: "Creed Aventus",
        description: "Культовый аромат с нотами ананаса, черной смородины и мускуса.",
        price: 35000,
        oldPrice: 0,
        category: "premium",
        volume: 100,
        rating: 4.9,
        reviews: 189,
        image: "https://images.unsplash.com/photo-1541643600914-78b084683601?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "hit",
        inStock: true,
        popular: true,
        notes: ["ананас", "смородина", "мускус", "ваниль"]
    },
    {
        id: 11,
        name: "Rasasi Hawas",
        description: "Современный арабский аромат с акватическими и фруктовыми нотами.",
        price: 4200,
        oldPrice: 0,
        category: "arabian",
        volume: 100,
        rating: 4.5,
        reviews: 78,
        image: "https://images.unsplash.com/photo-1590736969956-6d9c2a8d6971?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: null,
        inStock: true,
        popular: false,
        notes: ["акватик", "фрукты", "мускус", "цитрус"]
    },
    {
        id: 12,
        name: "Bvlgari Man In Black",
        description: "Темный и загадочный аромат с нотами рома, кожи и ванили.",
        price: 9200,
        oldPrice: 11000,
        category: "premium",
        volume: 100,
        rating: 4.6,
        reviews: 112,
        image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "sale",
        inStock: true,
        popular: true,
        notes: ["ром", "кожа", "ваниль", "табак"]
    },
    {
        id: 13,
        name: "Arabian Nights Gold",
        description: "Эксклюзивный арабский парфюм с золотыми акцентами.",
        price: 5500,
        oldPrice: 6500,
        category: "arabian",
        volume: 100,
        rating: 4.7,
        reviews: 45,
        image: "https://images.unsplash.com/photo-1590736969956-6d9c2a8d6971?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "sale",
        inStock: true,
        popular: true,
        notes: ["золото", "ладан", "ваниль", "древесина"]
    },
    {
        id: 14,
        name: "Versace Eros",
        description: "Соблазнительный аромат с нотами мяты, яблока и ванили.",
        price: 7500,
        oldPrice: 0,
        category: "affordable",
        volume: 100,
        rating: 4.6,
        reviews: 156,
        image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "hit",
        inStock: true,
        popular: true,
        notes: ["мята", "яблоко", "ваниль", "древесина"]
    },
    {
        id: 15,
        name: "Giorgio Armani Si",
        description: "Женственный аромат с нотами черной смородины и мускуса.",
        price: 9800,
        oldPrice: 11500,
        category: "premium",
        volume: 100,
        rating: 4.8,
        reviews: 98,
        image: "https://images.unsplash.com/photo-1541643600914-78b084683601?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "sale",
        inStock: true,
        popular: true,
        notes: ["смородина", "мускус", "ваниль", "цветы"]
    },
    {
        id: 16,
        name: "Afnan 9 PM",
        description: "Популярный арабский аромат со сладкими и фруктовыми нотами.",
        price: 3200,
        oldPrice: 0,
        category: "arabian",
        volume: 100,
        rating: 4.4,
        reviews: 67,
        image: "https://images.unsplash.com/photo-1590736969956-6d9c2a8d6971?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        badge: "new",
        inStock: true,
        popular: false,
        notes: ["фрукты", "ваниль", "древесина", "мускус"]
    }
];

// Экспорт данных для использования в других файлах
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PRODUCTS_DATA;
      }
